server:
  port: 8001

#应用名称
spring:
  application:
    name: account

#服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.10:8848
        username: nacos
        password: nacos

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/short-link?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: aa55ss55

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

